name: Gradle CI with actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.5.0

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: gradle-example
        #Hello moto
