name: Gradle CI with actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.5.0
      - name: Setup JF Cli
        uses: jfrog/setup-jfrog-cli@v4
        
      - name: Build with Gradle
        run: | 
          jf gradle clean artifactoryPublish
        working-directory: gradle-example
        #Hello moto -b path/to/build.gradle
