name: Gradle CI with actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gradle Build Action
        uses: gradle/actions/setup-gradle@v4
      - name: Setup JF Cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: ${{ secrets.JF_URL }}
          JF_PROJECT: ob1
        with:
          # Name of the OIDC provider as specified on the OIDC integration page in the JFrog Platform
          oidc-provider-name: mathieup-github
          
      - name: Build with Gradle
        run: | 
          jf gradle-config
          jf gradle init --overwrite
          jf gradle build artifactoryPublish
        working-directory: gradle-example
        #Hello moto -b path/to/build.gradle
        #jf rt bp gradle-example --url https://psemea.jfrog.io/artifactory/ob1-mat --access-token $JF_ACCESS_TOKEN
